// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9MQOsQ7FoqCj9Ib8dAZhL0UfrYDT5pXo',
    appId: '1:671601054665:web:bd790cc0713188d02bce18',
    messagingSenderId: '671601054665',
    projectId: 'cmsc23-dccaponpon',
    authDomain: 'cmsc23-dccaponpon.firebaseapp.com',
    storageBucket: 'cmsc23-dccaponpon.appspot.com',
    measurementId: 'G-L094QWVMTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBvLnZbmL8GUuXxg0xBu-Nc5npxJW0API',
    appId: '1:671601054665:android:742edd626c09f7a62bce18',
    messagingSenderId: '671601054665',
    projectId: 'cmsc23-dccaponpon',
    storageBucket: 'cmsc23-dccaponpon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgIQ3ZQp3zab9nqBDV9QhqjgwKZMS9aXc',
    appId: '1:671601054665:ios:81d22a4fb7cc9e8f2bce18',
    messagingSenderId: '671601054665',
    projectId: 'cmsc23-dccaponpon',
    storageBucket: 'cmsc23-dccaponpon.appspot.com',
    iosClientId: '671601054665-s6qal70b5vgo9r4dinlihi8e9oco3f9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgIQ3ZQp3zab9nqBDV9QhqjgwKZMS9aXc',
    appId: '1:671601054665:ios:81d22a4fb7cc9e8f2bce18',
    messagingSenderId: '671601054665',
    projectId: 'cmsc23-dccaponpon',
    storageBucket: 'cmsc23-dccaponpon.appspot.com',
    iosClientId: '671601054665-s6qal70b5vgo9r4dinlihi8e9oco3f9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
